language: java
install: mvn -B -U install clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true
script: mvn -B verify

jdk:
  - openjdk7
  - oraclejdk7

notifications:
  email: false

branches:
  only:
    - master
    - /^release.*$/
